// START1 OMIT
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'exoplat-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 10s

    target_groups:
      - targets: ['localhost:9090']
// STOP1 OMIT
// START2 OMIT
  - job_name: 'services-api'
    scrape_interval: 5s
    scrape_timeout: 10s

    dns_sd_configs:
    - refresh_interval: 15s
      type: 'SRV'
      names:
        - _api._http.prod.api.internal.suffix.io

  - job_name: 'services-gandalf'
    scrape_interval: 5s
    scrape_timeout: 10s

    dns_sd_configs:
    - refresh_interval: 15s
      type: 'SRV'
      names:
        - _gandalf._http.prod.gandalf.internal.suffix.io

rule_files:
  - /home/ubuntu/install/prometheus/prometheus-0.17.0.linux-amd64/alert_rules.yml
// STOP2 OMIT
